### ISSUE TITLE
Error when using "too large" interval as parameter in RadonParallelCircle

### ISSUE THREAD

**Issue by sebaseb98** [roflmaostc/RadonKA.jl#16]
#### Observed behaviour:

when executing `radon(zeros((10,10)), [0, π/4, π/2]; geometry=RadonParallelCircle(10, -5:5))` in my REPL, I get an error which originates from RadonKA/DK5pc/src/utils.jl line 60. My full error message is:
<img width="1513" alt="image" src="https://github.com/user-attachments/assets/0b1d6135-6f44-420c-8404-e56d2a41b17e">

#### possible solution:

As far as I understood the code, it could be enough to just add an `abs()` around the expression that becomes negative for too large values in the `in_height` array/range, as x_dist probably(?) should be the distance.

**Comment by roflmaostc** [comment]
Ah maybe I should throw errors upon creation of `RadonParallelCircle(10, -5:5))`.
But -5:5 is not supported for an array of size 10.
The limits are -4 and 4.
The center of an array with 10 elements is index 6. So 6 + 5 > 10, which means a ray would travel outside of the region of interest.

**Comment by roflmaostc** [comment]
Added better error message and updated docstring with
https://github.com/roflmaostc/RadonKA.jl/commit/9764d53d6051513b47524d664e006cb52a551cb3

**Comment by sebaseb98** [comment]
That should work as well, but in the real world you could also use a large CT-scanner for small things. That's what I wanted to try :D 
But of course it's up to you and if the implementation is designed in a way that this would be hard to fix otherwise, your solution is completely fine

**Comment by roflmaostc** [comment]
Yeah, in this case I guess you need to make the array larger or work around it.

**Comment by roflmaostc** [comment]
Better error message will be included soon in 0.6.2.
Functionality is the same in 0.6.1

https://github.com/JuliaRegistries/General/pull/113188
