### ISSUE TITLE
Understanding absorption implementation

### ISSUE THREAD

**Issue by stisa** [roflmaostc/RadonKA.jl#18]
Hi, thanks for the very nice package!

I am having some trouble understanding how the calculation of deposited energy is done. From what I understand, `value` is the absorbed energy in the voxel (rec) or of the sinogram (proj). You start from `value_in` (which seems to be the sinogram value in the reconstruction case, the value in the volume in the projection case), then  multiply a weight and the intensity calculated by Beer Lambert Law ( $`I = I_0*exp(-\alpha*d)`$ ). Here is what I don't understand: according to Kelly et al and Shusteff et al, the deposited energy at depth z is given by:

$\frac{dI(z)}{dz} = E_{abs}(z) = I_0 \cdot \alpha \cdot \exp(-\alpha\cdot z) \cdot t_{exposure}$

which is consistent with taking the derivative of the BLL in z.

but in your calculation, it appears to be something like https://github.com/roflmaostc/RadonKA.jl/blob/07fd44db74495f47cd3d5d04d8e8f3e9d3e04e0b/src/radon.jl#L261

$E_{abs}(z) = (weight) \cdot dz \cdot \text{(value in)} \cdot I_0 * \exp(-\alpha\cdot z)$

or in the µ_array case: https://github.com/roflmaostc/RadonKA.jl/blob/07fd44db74495f47cd3d5d04d8e8f3e9d3e04e0b/src/radon.jl#L271
$E_{abs}(z) = (weight) \cdot dz \cdot \text{(value in)} \cdot \prod_{k=0}^i (I_k \cdot \exp(-\alpha\cdot dz))$

Could you explain where these formulas come from? It looks like some approximation of $\frac{dI(z)}{dz}$ with a finite difference?

**Comment by roflmaostc** [comment]
I'm on my phone right now but yeah, I think it would be better to solve the integral to calculate the precise deposit value but I discretized it and simply multiplied by dz.

A small comment the case where the absorption spatially varies is not super battle tested.

Would you be open to share your application? Maybe I can help using this package for it :)

**Comment by stisa** [comment]
The application is just TVAM, I wanted to compare my implementation with others and maybe switch over since mine is a bit slow. Your implementation is really clear, but then I saw this discrepancy in the way we calculate the energy deposited and I got confused as to which one is correct.

I have my code written in python right now where I calculate the deposited energy roughly as:
```python
rec[x,:,:] += alpha * sino[:,theta,:] * exp(-alpha*x*voxelsize)
```
which is a rough translation of $`E_{abs}(x) = \alpha\cdot I_0  \cdot\exp(−\alpha\cdot x )`$ (assuming propagation direction is x here)

**Comment by roflmaostc** [comment]
I think you might do some discretization mistakes because the deposit value depends on the length of the intersection with the pixel.  And that can be different by a factor of sqrt(2) if you go along the diagonal of a pixel compared to horizontally for some angles.

But we could check a simple example with a single pixel on for 0° and 45°?

Btw, on another note: We are going to release another package for TVAM soon. This one is more powerful but also much more complex on the code base side.
But it allows to solve much more different use cases with TVAM.
I can ping you once it's released

**Comment by stisa** [comment]
Yeah in the case where you consider a rotated projection source it would probably give a discretization error. In my case with the rotating volume I think it should be fine? I'll see if I can write up a simple comparison of the depositions.

Please do ping me when the new package is out, I'd be really happy to take a look!

**Comment by roflmaostc** [comment]
I mean, your volume is descretized on a grid. So if you rotate your target, this also introduces some discretization errors.

Are you rotating your target? Or how is your python code implemented?

You are working in Freiburg, right?

**Comment by stisa** [comment]
I rotate the target/reconstruction volume, so the propagation direction is always aligned to an axis. Or rather, for the backprojection, I propagate along an axis then rotate the propagated area back so it is in the correct orientation and then sum the rotated contributon:
```python
# pseudo code for backproj
padded_target = pad_to_vialdiam( voxelize(stlmodel, voxelsizemm), diam=20)
sino = project(padded_target, alpha, voxelsizecm) # y,theta,z
rec = zeros_like(padded_target)
angles = arange(0,360,step=1.0)
x = arange(0, rec.shape[0])
for theta in angles:
  # using broadcasting so that shape(lhs)==shape(rhs)
  rec += rotate(alpha * sino[:,theta,:] * exp(-alpha*x*voxelsizecm), theta,) # using bilinear interp
````
I need to get around to putting up my version on github but waiting on some approvals.

Yep I work in Freiburg (DE, not CH)

**Comment by roflmaostc** [comment]
Yeah I see, that's similar to also how the VAMToolbox does it. I think this approach always has some memory overhead because the rotate result is stored in an array format.
But I never did benchmarking to verify.
I guess you've seen my SwissVAMyKnife.jl toolbox which uses RadonKA.jl as backend for the optimization.

But I think development will rather pause for SwissVAMyKnife.jl since I believe the new solution to be more powerful.
Let me definitely know if I can help in future to implement our new toolbox for your systems. 

Are you attending Photonics West?

**Comment by stisa** [comment]
Yeah it's similar to their implementation, although they use sparse matrices if I remember right. My pixels are pretty big thanks to the LCD so I can get away with putting everything in a big tensor in memory, I usually only need a tensor of 400x400x400. 
In vamtoolbox the code is a bit involved to read but I believe they do something like `E_abs(x) = alpha*dx*I_0*exp(-alpha*x)`

I don't know if I am coming to SPIE yet, I didn't sign up for a talk but I'm trying to see if I can make it anyway. I'm going to Formnext this week though.

**Comment by roflmaostc** [comment]
As promised, here out new tool!

https://github.com/rgl-epfl/drtvam

Please let me know if there is anything unclear, I'm certainly up to help since I use this every day :)

**Comment by stisa** [comment]
Nice, thanks for letting me know! I'll definitely give it a try :)
